export const CURRENCY_RULES ={
    pairName: 'USDT'
};

export const NOT_EXIST_IN_FUTURE = [
    'BTTUSDT', 'TRUUSDT', 'CITYUSDT', 'USDSBUSDT', 'AUDUSDT', 'BCHSVUSDT', 'MDXUSDT', 'DATAUSDT', 'DEGOUSDT',
    'MINAUSDT', 'CAKEUSDT', 'ONGUSDT', 'GNOUSDT', 'PERLUSDT', 'ACMUSDT', 'BCHABCUSDT', 'LTOUSDT', 'TWTUSDT',
    'ILVUSDT', 'BNBBULLUSDT', 'LSKUSDT', 'STPTUSDT', 'XZCUSDT', 'HARDUSDT', 'YGGUSDT', 'SYSUSDT', 'PONDUSDT',
    'SANDUSDT', 'VITEUSDT', 'USDTBRL', 'STRATUSDT', 'BNBBEARUSDT', 'USDSUSDT', 'VENUSDT', 'DUSKUSDT'
];